components/footnotes.js
components/heading.js
components/main.js
components/note.js
components/picture.js
components/pictureoverlay.js
components/sectionedlist.js
components/sidebarpictures.js
components/sidebarsplit.js
components/split-when-small.js
components/subheading.js
components/textname.js
components/twocolumns.js
components/workname.js
pages/bio.js
pages/dict.js
pages/error.js
pages/helpers/strings.js
pages/helpers/types.js
pages/index.js
pages/mentions.js
pages/poets-looks.js
pages/search.js
tools/build-static.js

Bladring i portrætter

---

fdirs/drachmann/1872.xml

Drachmann: Digte (1872)

---

fdirs/kaalund/1840k.xml
fdirs/kaalund/1844.xml
fdirs/kaalund/1845.xml
fdirs/kaalund/1858.xml
pages/helpers/types.js
pages/text.js
tools/build-static.js
tools/libs/caching.js

Håndter varianter

---

fdirs/stuckenberg/1886.xml

Stuckenberg: Digte (1886)

---

fdirs/claussen/1899.xml

Sophus Claussen: Pilefløjter (1899)

---

fdirs/claussen/1904.xml

Komplet og færdig. Der er dog ting, der skal efterses (jvf. issues), og sektionerne skal der nok gåes over med en fin kam.

Djævlerier (1904) rettet ind efter førsteudgaven

---

fdirs/claussen/1904.xml

En håndfuld justeringer til førsteudgaven. Dette er blot en test!

Claussen: Djævlerier (1904)

---

fdirs/claussen/1904.xml
fdirs/claussen/1910.xml

Hermed rettet ind efter førsteudgaven.

Sophus Claussens "Eroter og Fauner"

---

fdirs/claussen/1904.xml
fdirs/claussen/1912.xml

Rettet ind efter førsteudgaven med sidetal.

Sophus Claussen: "Danske Vers"

---

fdirs/claussen/1917.xml

Klargjort efter førstegaven og til faksimiler.

Sophus Claussen: "Fabler" (1917)

---

Asterkrandsen (1817).txt

Rahbek: Asterkrandsen (1817)

---

fdirs/drachmann/1879.xml
fdirs/drachmann/andre.xml

Rettes ind efter førsteudgaven.

Drachmann: "Ungdom i Digt og Sang" (1879)

---

fdirs/drachmann/1881.xml

Drachmann: "Gamle Guder og nye"

---

fdirs/hoffmann/1899.xml

Nøgleord tilføjet. Issue lukket.

Nøgleord tilføjet

---

fdirs/hoffmann/1905.xml

Nøgleord og en enkelt rettelse. Issue lukket.

Nøgleord og en enkelt rettelse.

---

1842.txt
fdirs/longfellow/1842.xml
fdirs/uhland/andre.xml

Færdiggørelse efter andenudgaven.

Longfellow: "Ballads and Other Poems" (1842)

---

fdirs/longfellow/1842.xml

Rettelser medsamt et forord til The Skeleton in Armour.

Rettelser til Longfellow: "Ballads and Other Poems" (1842)

---

fdirs/horn/1872.xml

Fr. Winkel Horn: Digte (1872) - Rettelser

---

fdirs/lyhne/1913.xml

Knud Lyhne: Provinsbyens Sange (1913) - Rettelser

---

fdirs/henriksen/1915s.xml

Ganske få rettelser samt et par nøgleord indført.

Hans Henriksen: Solhvervstider (1915) - Rettelser

---

fdirs/gregersen/1875.xml

Vilhelm Gregersen: Nogle Digte (1875) - Rettelser

---

fdirs/hemans/andre.xml

Felicia Hemans: Andre digte - Rettelser

---

fdirs/oldenburg/1844.xml

Rettelser, samt en fundet original af en oversættelse "Vuggevisen" (se TODO).

Theodore Oldenburg: Mindeblade (1844) - Rettelser

---

fdirs/petersen/1933.xml

Nis Petersen: En Drift Vers (1933) - Rettelser

---

fdirs/gerson/1845.xml

Gerson: Digte for Børn (1845) - Rettelse

---

fdirs/petersen/1935.xml

Nogle ganske få rettelser og et nøgleord.

Nis Petersen: Til en Dronning (1935) - Rettelser

---

fdirs/nerval/1854.xml

Et manglende nøgleord tilføjet.

Nerval: Les Chimères (1854) - Nøgleord

---

fdirs/roerdam/1897.xml

Valdemar Rørdam: Tre Strænge (1897) - Rettelser

---

fdirs/baudelaire/1866.xml
fdirs/keats/post.xml
fdirs/wormw/andre.xml
fdirs/wotton/andre.xml

<i> i <title> fikset
